export const PRODUCTS = [
  {
    id: 'zarr-e-talai-haldi',
    slug: 'zarr-e-talai-haldi',
    category: 'Spices',
    tag: 'Best Seller',
    name: 'Zarr-e-Talai Haldi',
    subtitle: 'Golden Stone-Ground Turmeric',
    origin: 'Kashmir Highlands, Pakistan',
    price: 350,
    weights: ['100g', '200g', '500g'],
    priceMap: { '100g': 200, '200g': 350, '500g': 750 },
    image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=900&q=85&fit=crop',
    imageDetail: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=1200&q=90&fit=crop',
    imageAlt: 'Stone-ground turmeric powder with raw roots',
    heroDesc: 'Not spice. Cultural memory, ground into gold.',
    desc: 'Sourced from the sun-drenched highlands of Kashmir, our turmeric is hand-harvested, slow sun-dried, and cold-ground on ancient granite mills. The result is a deep amber powder with 5%+ curcumin — the highest potency achievable, preserved by the absence of heat.',
    storyTitle: 'From Himalayan Soil to Stone',
    story: 'Our Zarr-e-Talai — meaning "gilded gold" — travels from the terraced farms of Kashmir Valley, where turmeric has grown for over a thousand years. Farmers hand-select roots at peak maturity. They are dried for 30 days in open mountain air before reaching our stone mills. This is not a commodity. This is provenance.',
    benefits: [
      '5%+ curcumin content — premium medicinal grade',
      'Cold-ground preserves volatile essential oils',
      'No artificial colour, fragrance, or fillers',
      'Anti-inflammatory, digestive, immune-supporting',
      'Batch-numbered with origin traceability',
    ],
    process: 'Our granite mills rotate at 40 RPM — a fraction of industrial speed. No heat is generated. The aromatic oils remain locked inside every particle. This is why Kohan turmeric smells like a spice market, not a plastic packet.',
  },
  {
    id: 'hayat-mix-atta',
    slug: 'hayat-mix-atta',
    category: 'Flour',
    tag: 'Premium',
    name: 'Hayat Mix Atta',
    subtitle: 'Seven-Grain Heritage Flour',
    origin: 'Punjab Plains, Pakistan',
    price: 480,
    weights: ['500g', '1kg', '2kg'],
    priceMap: { '500g': 280, '1kg': 480, '2kg': 880 },
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=900&q=85&fit=crop',
    imageDetail: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=1200&q=90&fit=crop',
    imageAlt: 'Seven-grain stone-ground flour with raw grains',
    heroDesc: 'Seven ancient grains. One timeless bread.',
    desc: "A blend of Pakistan's most nourishing heritage grains — wheat, barley, millet, sorghum, corn, oats, and amaranth — ground whole on cold stone, preserving the bran, germ, and every nutrient that industrial rollers discard in the name of shelf life.",
    storyTitle: 'The Grains Our Grandmothers Knew',
    story: "Punjab's breadbasket has fed civilisations. Hayat — meaning 'life' — honours that legacy. We source seven heritage grain varieties from small Punjab farms, blend them by hand in precise ratios developed over three years of testing, and stone-grind the whole blend without separation. The bran stays. The germ stays. Life stays.",
    benefits: [
      'Whole-grain: bran and germ fully intact',
      'High dietary fibre — aids digestion and satiety',
      'Lower glycaemic impact than white flour',
      'Rich in B-vitamins, iron, and magnesium',
      'No bleaching agents, no preservatives',
    ],
    process: 'Stone grinding produces flour with a natural warmth — not from heat, but from the living texture of whole grain. The particles are irregular, as nature intended. This irregularity is what gives Hayat Atta its superior taste and nutritional profile.',
  },
  {
    id: 'dardari-lal-mirch',
    slug: 'dardari-lal-mirch',
    category: 'Spices',
    tag: null,
    name: 'Dardari Lal Mirch',
    subtitle: 'Sun-Dried Balochi Red Chilli',
    origin: 'Balochistan Highlands, Pakistan',
    price: 320,
    weights: ['100g', '200g', '500g'],
    priceMap: { '100g': 180, '200g': 320, '500g': 680 },
    image: 'https://images.unsplash.com/photo-1601648764658-cf37e8c89b70?w=900&q=85&fit=crop',
    imageDetail: 'https://images.unsplash.com/photo-1601648764658-cf37e8c89b70?w=1200&q=90&fit=crop',
    imageAlt: 'Deep red stone-ground chilli powder with whole dried chillies',
    heroDesc: 'Heat with character. Fire with heritage.',
    desc: "Balochistan's long red chillies, altitude-dried in the clean mountain air for 45 days, then stone-ground seeds and all. The colour is naturally deep crimson — no dye, no artificial enhancement. The heat is complex, layered, and fragrant.",
    storyTitle: "Balochistan's Scarlet Treasure",
    story: "Dardari — meaning 'of the highlands' — pays homage to Balochistan's spice tradition. These are not commodity chillies. They are a specific long-pod variety grown at altitude, where cool nights and intense sun produce exceptional capsaicin complexity. Families have grown this variety on the same terraced fields for generations.",
    benefits: [
      'Natural deep red colour — zero artificial dye',
      'Complex heat profile: initial warmth, lingering finish',
      'Rich in Vitamin C and antioxidants',
      'Ground with seeds for full-spectrum heat',
      'Altitude-dried for concentrated flavour',
    ],
    process: "When Dardari Lal Mirch hits hot oil, the colour blooms into a deep, lacquered red. That visual transformation — impossible to replicate with machine-ground, heat-damaged chilli — is the signature of genuine cold-ground spice.",
  },
  {
    id: 'kohan-garam-masala',
    slug: 'kohan-garam-masala',
    category: 'Blends',
    tag: 'Signature',
    name: 'Kohan Garam Masala',
    subtitle: 'Twelve-Spice Royal Blend',
    origin: 'Multi-Region, Pakistan',
    price: 540,
    weights: ['50g', '100g', '250g'],
    priceMap: { '50g': 320, '100g': 540, '250g': 1100 },
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=900&q=85&fit=crop',
    imageDetail: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1200&q=90&fit=crop',
    imageAlt: 'Twelve whole spices blended into royal garam masala',
    heroDesc: 'Twelve spices. Three generations. One blend.',
    desc: 'Twelve whole spices — each individually sourced from its ideal regional origin, individually roasted over wood flame, cooled, then blended by hand before a single, ceremonial stone-grind. The resulting masala is complex, layered, and impossible to replicate from pre-ground components.',
    storyTitle: 'A Recipe Three Generations in the Making',
    story: 'This recipe existed before Kohan had a name. It was a family formula — adjusted over decades, debated across dinner tables, refined through thousands of pots of biryani and nihari. When Kohan was founded, this blend was the only product we launched, because it deserved to be first.',
    benefits: [
      '12 individually roasted whole spices',
      'Each spice sourced from its origin region',
      'Single stone-grind pass — no re-milling',
      'No starch, salt, or flow agents',
      'Batch-dated and numbered',
    ],
    process: 'We roast each spice separately over measured wood flame. Each has a different ideal temperature and duration. After cooling for 12 hours, they are hand-blended by weight, then passed through the stone mill exactly once. A second pass would mute the complexity we worked to create.',
  },
];

export function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug) || null;
}
